# Generates the Apps Script copy of the web UI from web/ (single source of truth).
#   web/style.css   -> src/ui_css.html      (<style>…</style>)
#   web/<name>.js   -> src/ui_<name>.html   (<script>…</script>)
#   web/index.html  -> src/Index.html       (local <link>/<script src> replaced by include() scriptlets)
# Works on Windows PowerShell 5.1 and PowerShell 7 (GitHub Actions ubuntu runner).
#   Windows:  powershell -ExecutionPolicy Bypass -File tools/build-appsscript.ps1
#   CI/Linux: pwsh tools/build-appsscript.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$web = Join-Path $root 'web'
$src = Join-Path $root 'src'
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Read-Text($path) { [IO.File]::ReadAllText($path, $utf8) -replace "`r`n", "`n" }
function Write-Text($path, $text) { [IO.File]::WriteAllText($path, $text, $utf8); Write-Host "  wrote $(Split-Path -Leaf $path)" }

$banner = "<!-- GENERATED by tools/build-appsscript.ps1 from web/ - do not edit; edit web/ and rebuild -->`n"

Write-Host "Building Apps Script UI from $web"

Write-Text (Join-Path $src 'ui_css.html') ($banner + "<style>`n" + (Read-Text (Join-Path $web 'style.css')) + "</style>`n")

$html = Read-Text (Join-Path $web 'index.html')
$html = $html -replace '<link rel="stylesheet" href="style\.css">', "<?!= include('ui_css'); ?>"

foreach ($js in Get-ChildItem -Path $web -Filter '*.js') {
  $name = [IO.Path]::GetFileNameWithoutExtension($js.Name)
  $body = Read-Text $js.FullName
  if ($body -match '</script') { throw "$($js.Name) contains '</script' which would break the inline <script> in Apps Script" }
  Write-Text (Join-Path $src "ui_$name.html") ($banner + "<script>`n" + $body + "</script>`n")
  $html = $html -replace ('<script src="' + [regex]::Escape($js.Name) + '"></script>'), "<?!= include('ui_$name'); ?>"
}

if ($html -match '(href|src)="(?!https?:)[^"]+\.(css|js)"') { throw "index.html still references a local file: $($Matches[0])" }
# Banner goes after <!doctype> so the page doesn't drop into quirks mode
$index = $html -replace '^(<!doctype html>\n)', ('$1' + $banner)
Write-Text (Join-Path $src 'Index.html') $index

# --- Copy-paste bundle (no clasp needed): build/apps-script/
# 4 files to paste into Extensions > Apps Script:
#   Code.gs  = every src/*.js concatenated     Index.html = UI with CSS/JS inlined
#   confirm.html (as-is)                        appsscript.json (manifest)
$bundle = Join-Path $root 'build/apps-script'
New-Item -ItemType Directory -Force -Path $bundle | Out-Null
$code = "// GENERATED by tools/build-appsscript.ps1 - all files from src/*.js in one file for copy-paste`n"
foreach ($f in Get-ChildItem -Path $src -Filter '*.js' | Sort-Object Name) {
  $code += "`n// ============================================================ $($f.Name)`n" + (Read-Text $f.FullName)
}
Write-Text (Join-Path $bundle 'Code.gs') $code
$inlined = [regex]::Replace($index, "<\?!= include\('(\w+)'\); \?>", {
  param($m) Read-Text (Join-Path $src ($m.Groups[1].Value + '.html'))
})
Write-Text (Join-Path $bundle 'Index.html') $inlined
Copy-Item (Join-Path $src 'confirm.html') $bundle -Force
Copy-Item (Join-Path $src 'appsscript.json') $bundle -Force
Write-Host "  bundle -> $bundle"
Write-Host 'Done.'
